<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RavenTargetPlatform>NeoCLR</RavenTargetPlatform>
    <RavenMetadataFormat>NeoCLR</RavenMetadataFormat>
    <RavenNeoClrBootstrapOwnership>../System.Runtime/ownership.json</RavenNeoClrBootstrapOwnership>
    <RavenNeoClrObjectLibrary>System.Runtime</RavenNeoClrObjectLibrary>
    <RavenNeoClrAsyncLibrary>System.Runtime</RavenNeoClrAsyncLibrary>
    <RavenNeoClrBootstrapIntrinsics>true</RavenNeoClrBootstrapIntrinsics>
  </PropertyGroup>
</Project>
