#!/usr/bin/env python3
"""Verify or refresh the RavenDoc compiler-reference snapshot."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import xml.etree.ElementTree as ET
from api_inventory import public_types

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / 'api-docs'
MANIFEST = DOCS / 'snapshot.json'


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def inputs():
    # The reference assembly is generated by these declarations and projections.
    paths = list((ROOT / 'docs/experiments/raven-target').glob('*.cs'))
    paths += list((ROOT / 'runtime/raven/src').rglob('*.rvn'))
    paths += [DOCS / name for name in ('NeoCLR.CoreProbe.xml', 'types.json', 'exclusions.json', 'manual-types.json')]
    return {str(p.relative_to(ROOT)): digest(p) for p in sorted(paths)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--refresh', type=Path, metavar='CORE_DLL', help='Snapshot a freshly generated compiler reference assembly')
    parser.add_argument('--check', action='store_true', help='Check reference inputs and checksum')
    args = parser.parse_args()
    assembly = DOCS / 'reference/NeoCLR.CoreProbe.dll'
    if args.refresh:
        assembly.parent.mkdir(parents=True, exist_ok=True)
        if args.refresh.resolve() != assembly.resolve():
            shutil.copyfile(args.refresh, assembly)
        (DOCS / 'types.json').write_text(json.dumps(public_types(assembly), indent=2) + '\n')
        MANIFEST.write_text(json.dumps({'assemblySha256': digest(assembly), 'inputs': inputs()}, indent=2) + '\n')
    inventory = public_types(assembly)
    if json.loads((DOCS / 'types.json').read_text()) != inventory:
        raise ValueError('Public API inventory is stale; refresh the reference snapshot. Public types must not be filtered out.')
    recorded = json.loads(MANIFEST.read_text())
    if recorded['inputs'] != inputs() or recorded['assemblySha256'] != digest(assembly):
        raise ValueError('API reference snapshot is stale. See api-docs/README.md to refresh from current metadata and XML.')
    shutil.copyfile(DOCS / 'NeoCLR.CoreProbe.xml', assembly.with_suffix('.xml'))
    print('Checked RavenDoc reference assembly and source fingerprints', flush=True)
    if not args.check:
        subprocess.run(['python3', str(ROOT / 'scripts/build-website.py')], check=True)


if __name__ == '__main__':
    main()
