#!/usr/bin/env python3
"""Build DocFX reference pages, or refresh their metadata snapshot from a core DLL."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / 'api-docs'
MANIFEST = DOCS / 'snapshot.json'


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def inputs():
    # The reference assembly is generated by these declarations and projections.
    paths = list((ROOT / 'docs/experiments/raven-target').glob('*.cs'))
    paths += list((ROOT / 'runtime/raven/src/System/Tasks').glob('*.rvn'))
    paths += list((ROOT / 'runtime/raven/src/System/Concurrency').glob('*.rvn'))
    paths += [DOCS / name for name in ('NeoCLR.CoreProbe.xml', 'filter.yml', 'docfx.json')]
    paths += [ROOT / '.config/dotnet-tools.json']
    return {str(p.relative_to(ROOT)): digest(p) for p in sorted(paths)}


def generated():
    return {str(p.relative_to(DOCS)): digest(p) for p in sorted((DOCS / 'api').glob('*.yml'))}


def check_descriptions():
    members = {m.attrib['name']: m for m in ET.parse(DOCS / 'NeoCLR.CoreProbe.xml').findall('./members/member')}
    count = 0
    for path in (DOCS / 'api').glob('*.yml'):
        # DocFX emits the items before its supporting reference table. Check only
        # published items, not types mentioned by signatures or overload groups.
        items = path.read_text().split('\nreferences:', 1)[0]
        for uid in re.findall(r'^  commentId: ([TMPF]:.+)$', items, re.M):
            member = members.get(uid)
            if member is None or member.find('summary') is None or not ''.join(member.find('summary').itertext()).strip():
                raise ValueError('Missing API summary: ' + uid)
            count += 1
    if count == 0:
        raise ValueError('No documented API items generated')
    print(f'Checked summaries for {count} generated API items', flush=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--refresh', type=Path, metavar='CORE_DLL', help='Regenerate the checked-in YAML from a freshly generated reference assembly')
    parser.add_argument('--check', action='store_true', help='Check snapshot inputs and descriptions without building HTML')
    args = parser.parse_args()
    if args.refresh:
        staging = ROOT / 'target/api-docs/input'
        staging.mkdir(parents=True, exist_ok=True)
        assembly = staging / 'NeoCLR.CoreProbe.dll'
        if args.refresh.resolve() != assembly.resolve():
            shutil.copyfile(args.refresh, assembly)
        shutil.copyfile(DOCS / 'NeoCLR.CoreProbe.xml', assembly.with_suffix('.xml'))
        shutil.rmtree(DOCS / 'api', ignore_errors=True)
        subprocess.run(['dotnet', 'tool', 'run', 'docfx', 'metadata', str(DOCS / 'docfx.json'), '--warningsAsErrors'], cwd=ROOT, check=True)
        check_descriptions()
        MANIFEST.write_text(json.dumps({'assemblySha256': digest(assembly), 'inputs': inputs(), 'generated': generated()}, indent=2) + '\n')
    recorded = json.loads(MANIFEST.read_text())
    if recorded['inputs'] != inputs() or recorded['generated'] != generated():
        raise ValueError('API snapshot is stale. See api-docs/README.md to refresh from current metadata and XML.')
    check_descriptions()
    if not args.check:
        subprocess.run(['dotnet', 'tool', 'run', 'docfx', 'build', str(DOCS / 'docfx.json'), '--warningsAsErrors'], cwd=ROOT, check=True)


if __name__ == '__main__':
    main()
