#!/usr/bin/env python3
"""Generate default simple case folding from pinned Unicode 17.0.0 CaseFolding.txt.
Usage: python3 scripts/generate-string-case-folding.py /path/to/CaseFolding.txt
Source: https://www.unicode.org/Public/17.0.0/ucd/CaseFolding.txt
Normal builds use the checked-in table, without network access or Python.
"""
import hashlib
from pathlib import Path
import sys

raw = Path(sys.argv[1]).read_bytes()
expected = "ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183"
if hashlib.sha256(raw).hexdigest() != expected:
    raise SystemExit("CaseFolding.txt does not match the pinned Unicode 17.0.0 SHA-256")
pairs = []
for line in raw.decode().splitlines():
    fields = line.split("#", 1)[0].strip().split(";")
    if len(fields) < 3 or fields[1].strip() not in ("C", "S"):
        continue
    source = int(fields[0], 16)
    targets = fields[2].split()
    assert len(targets) == 1
    pairs.append((source, int(targets[0], 16)))
assert pairs == sorted(set(pairs))
lines = [
    "// Generated by scripts/generate-string-case-folding.py; do not edit.",
    "// Unicode 17.0.0 CaseFolding.txt, SHA-256 " + expected,
    "// Unicode data license: ../third-party/unicode/LICENSE.txt",
    "// Default simple folding: C and S mappings; no F expansions or T tailoring.",
    "pub(super) const MAPPINGS: &[(u32, u32)] = &[",
]
lines += [f"    (0x{source:04X}, 0x{target:04X})," for source, target in pairs]
lines.append("];\n")
Path(__file__).resolve().parents[1].joinpath("src/string_case_folding.rs").write_text("\n".join(lines))
