#!/usr/bin/env python3
"""Regenerate the checked-in BMP category table from pinned Unicode 16.0.0 data.
Usage: python3 scripts/generate-char-categories.py /path/to/UnicodeData.txt
Download: https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt
Normal builds use the generated file and require no network or Python.
"""
import hashlib
from pathlib import Path
import sys

raw = Path(sys.argv[1]).read_bytes()
expected = "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f"
if hashlib.sha256(raw).hexdigest() != expected:
    raise SystemExit("UnicodeData.txt does not match the pinned Unicode 16.0.0 SHA-256")
# Internal values follow .NET UnicodeCategory; no public enum is introduced here.
names = "Lu Ll Lt Lm Lo Mn Mc Me Nd Nl No Zs Zl Zp Cc Cf Cs Co Pc Pd Ps Pe Pi Pf Po Sm Sc Sk So Cn".split()
categories = [29] * 65536
first = None
for line in raw.decode().splitlines():
    code, name, category, *_ = line.split(";")
    code = int(code, 16)
    if code > 0xFFFF:
        continue
    if name.endswith(", First>"):
        first = code
    else:
        start = first if name.endswith(", Last>") else code
        assert start is not None
        categories[start:code + 1] = [names.index(category)] * (code + 1 - start)
        first = None
assert first is None
lines = [
    "// Generated by scripts/generate-char-categories.py; do not edit.",
    "// Unicode 16.0.0 UnicodeData.txt, SHA-256 " + expected,
    "// Unicode data license: ../third-party/unicode/LICENSE.txt",
    "// Inclusive range ends and internal .NET-compatible category IDs.",
    "pub(super) const RANGES: &[(u16, u8)] = &[",
]
for i, category in enumerate(categories):
    if i == 65535 or categories[i + 1] != category:
        lines.append(f"    (0x{i:04X}, {category}),")
lines.append("];\n")
Path(__file__).resolve().parents[1].joinpath("src/char_categories.rs").write_text("\n".join(lines))
