#!/usr/bin/env python3
"""Generate Unicode 17 full default casing tables from a directory of pinned UCD files.
Normal builds use the checked-in tables; no download or host Unicode version needed.
"""
import hashlib
from pathlib import Path
import sys

HASHES = {
    'UnicodeData.txt': '2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c',
    'SpecialCasing.txt': 'efc25faf19de21b92c1194c111c932e03d2a5eaf18194e33f1156e96de4c9588',
    'DerivedCoreProperties.txt': '24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08',
}
files = {}
for name, digest in HASHES.items():
    raw = (Path(sys.argv[1]) / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest:
        raise SystemExit(f'{name} does not match pinned Unicode 17.0.0 SHA-256')
    files[name] = raw.decode()
lower, upper = {}, {}
for line in files['UnicodeData.txt'].splitlines():
    fields = line.split(';')
    source = int(fields[0], 16)
    for table, index in ((lower, 13), (upper, 12)):
        if fields[index]:
            table[source] = [int(fields[index], 16)]
contexts = set()
for line in files['SpecialCasing.txt'].splitlines():
    fields = line.split('#', 1)[0].strip().split(';')
    if len(fields) < 5:
        continue
    condition = fields[4].strip()
    if condition:
        if not any(part in ('tr', 'az', 'lt') for part in condition.split()):
            contexts.add(condition)
        continue
    source = int(fields[0], 16)
    for table, index in ((lower, 1), (upper, 3)):
        table[source] = [int(value, 16) for value in fields[index].split()]
assert contexts == {'Final_Sigma'}, contexts
properties = {'Cased': [], 'Case_Ignorable': []}
for line in files['DerivedCoreProperties.txt'].splitlines():
    fields = line.split('#', 1)[0].strip().split(';')
    if len(fields) != 2 or fields[1].strip() not in properties:
        continue
    ends = fields[0].strip().split('..')
    properties[fields[1].strip()].append((int(ends[0], 16), int(ends[-1], 16)))
lines = ['// Generated by scripts/generate-string-casing.py; do not edit.',
         '// Unicode 17.0.0 full default casing; Final_Sigma is implemented in string_casing.rs.',
         '// Sources: https://www.unicode.org/Public/17.0.0/ucd/',
         '// Unicode data license: ../third-party/unicode/LICENSE.txt']
lines += [f'// {name} SHA-256 {digest}' for name, digest in HASHES.items()]
for name, table in (('LOWER', lower), ('UPPER', upper)):
    lines.append(f'pub(super) const {name}: &[(u32, &str)] = &[')
    for source, targets in sorted(table.items()):
        if targets != [source]:
            value = ''.join('\\u{' + f'{target:X}' + '}' for target in targets)
            lines.append(f'    (0x{source:04X}, "{value}"),')
    lines.append('];')
for name, ranges in properties.items():
    assert ranges == sorted(ranges)
    lines.append(f'pub(super) const {name.upper()}: &[(u32, u32)] = &[')
    lines += [f'    (0x{start:04X}, 0x{end:04X}),' for start, end in ranges]
    lines.append('];')
Path(__file__).resolve().parents[1].joinpath('src/string_casing_data.rs').write_text('\n'.join(lines) + '\n')
